# pytorch112.yaml
# conda install -f pytorch112.yml
# conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.6 -c pytorch -c conda-forge
# Notice that if cpu-version pytorch was installed, it means GPU-pytorch for your version combination not exists on the channels. Try to relax the version limitation, for example, use  `cudatoolkit`` instead of `cudatoolkit=11.3`. Related packages: python, pytorch,torchvision, torchaudio, cudatoolkit
channels:
  - pytorch
  - conda-forge
dependencies:
- python=3.10
- pytorch=1.12
- torchvision
- cudatoolkit
- pytorch-lightning=1.7
- torchmetrics=0.9.3
- scikit-learn
- h5py
- matplotlib
- imgaug=0.4.0 # replace this with kornia
- albumentations=1.0.3 # replace this with kornia
- pyside2
- kornia
- jsonargparse[signatures]
- seaborn
- tabulate
- tqdm
- ipykernel
- ipympl
- ipython
- sphinx
# - sphinx-rtd-theme # if failed, install use conda instead of micromamba
- sphinxcontrib-mermaid # if failed, install use conda instead of micromamba
# - deeplake # pip install
- notebook # export notebook as HTML
- nbconvert # export notebook as HTML
- levenshtein # string similarity; for exception pharsing.
- imagesize # fetch image size without loading the full image.
- rich[jupyter] # pretty terminal
- regex # Support more than builtin re module.